# Generated by Django 2.0.2 on 2018-03-10 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justin_laureano', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Projects',
        ),
    ]
