# Generated by Django 2.0.2 on 2018-03-10 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justin_laureano', '0002_auto_20180310_2328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
