# Generated by Django 2.0.2 on 2018-02-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LunchMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50)),
                ('item', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
