# Generated by Django 2.0.2 on 2018-02-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gathering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchmenu',
            name='type',
            field=models.CharField(blank=True, choices=[('Lunch Soups', 'Lunch Soups'), ('Lunch Salads', 'Lunch Salads'), ('Lunch Fare', 'Lunch Fare'), ('Lunch Sides', 'Lunch Sides'), ('Lunch Sweets', 'Lunch Sweets')], max_length=50),
        ),
    ]
