# Generated by Django 2.0.2 on 2018-02-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gathering', '0002_auto_20180220_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchmenu',
            name='price',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
