# Generated by Django 2.0.2 on 2018-02-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gathering', '0004_auto_20180220_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchmenu',
            name='add_on',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lunchmenu',
            name='add_on_price',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
