# Generated by Django 2.0.2 on 2018-02-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gathering', '0008_winemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnvilMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Food', 'Food'), ('Kentucky Straight Bourbon', 'Kentucky Straight Bourbon'), ('Bourbon Whiskey, Blends, Irish, Miscreants', 'Bourbon Whiskey, Blends, Irish, Miscreants'), ('Rye Whiskey', 'Rye Whiskey'), ('Single Malt Scotch Whisky', 'Single Malt Scotch Whisky'), ('Blended Scotch Whisky', 'Blended Scotch Whisky'), ('The Elite', 'The Elite')], max_length=50)),
                ('item', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=800)),
                ('price', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
