# Generated by Django 2.0.2 on 2018-03-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gathering', '0009_anvilmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=120)),
                ('event_time', models.CharField(max_length=120)),
                ('event_venue', models.CharField(blank=True, choices=[('The Gathering', 'The Gathering'), ('The Gathering Wine', 'The Gathering Wine'), ('The Anvil', 'The Anvil'), ('The Courtyard Patio', 'The Courtyard Patio')], max_length=15)),
                ('event_description', models.TextField(blank=True, max_length=800)),
            ],
        ),
    ]
