# Generated by Django 2.0.2 on 2018-03-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gathering', '0011_auto_20180301_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='event_image',
            field=models.ImageField(default='static/images/logo.png', upload_to='static/image/live_events/'),
        ),
    ]
